version: "3"

volumes:
  mysql_data: {}

services:
  frontend:
    build:
      context: ./letterman-front
      args:
        API_URL: "*"
    volumes:
      - ./letterman-front:/frontend
    restart: always
    tty: true

  db:
    container_name: mysqldb
    image: mysql:latest
    env_file :
      - ./letterman-back/backend/devenvs/mysqldb.env
    volumes:
     - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    build: ./letterman-back/backend
    command: >
      bash -c "python3 manage.py makemigrations &&
               python3 manage.py migrate &&
               python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./letterman-back/backend:/app
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx 
    ports:
      - 80:80
    depends_on:
      - frontend