version: "3"

volumes:
  static_volume: null
  media_volume: null
  build_folder: null
  mysql_data: {}

services:
  nginx:
    build:
      context: ./nginx 
      dockerfile: Dockerfile
    volumes:
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
      - build_folder:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  db:
    container_name: mysqldb
    image: mysql:latest
    env_file :
      - ./letterman-back/backend/devenvs/mysqldb.env
    volumes:
     - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    build: ./letterman-back/backend
    container_name: backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8080 --timeout 240
    ports:
      - "8080:8080"
    volumes:
      - ./letterman-back/backend:/app
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./letterman-front
      args:
        API_URL: "*"
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    volumes:
      - ./letterman-front:/frontend
      - build_folder:/frontend/build
      - ./letterman-front/node_modules/:/frontend/node_modules 
    restart: always
    tty: true

